openapi: 3.0.3

info:
  version: 0.0.1
  title: AzNum2Words API
  description: |
    REST API for converting number to words in Azerbaijani language

servers:
  - url: http://localhost:8080

tags:
  - name: Converter
    description: API for converting number to words in Azerbaijani language
  - name: Health
    description: API related to the health of the service

paths:
  /api/v1/conversion/to-word:
    post:
      summary: Convert number to words in Azerbaijani
      operationId: ConvertNumberToWord
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConvertNumberToWords'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConvertNumberToWordsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnknownError'
      parameters:
        - name: x-correlation-id
          in: header
          schema:
            type: string
          required: false
          description: The unique request identifier

  /api/v1/conversion/to-number:
    post:
      summary: Convert words in Azerbaijani to number
      operationId: ConvertWordsToNumber
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConvertWordsToNumber'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConvertWordsToNumberResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnknownError'
      parameters:
        - name: x-correlation-id
          in: header
          schema:
            type: string
          required: false
          description: The unique request identifier

  /api/v1/conversion/date-to-words:
    post:
      summary: Convert date to words in Azerbaijani
      operationId: ConvertDateToWords
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConvertDateToWords'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Word'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnknownError'
      parameters:
        - name: x-correlation-id
          in: header
          schema:
            type: string
          required: false
          description: The unique request identifier

  /api/v1/conversion/time-to-words:
    post:
      summary: Convert time to words in Azerbaijani
      operationId: ConvertTimeToWords
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConvertTimeToWords'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Word'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnknownError'
      parameters:
        - name: x-correlation-id
          in: header
          schema:
            type: string
          required: false
          description: The unique request identifier

  /api/v1/conversion/datetime-to-words:
    post:
      summary: Convert date and time to words in Azerbaijani
      operationId: ConvertDateTimeToWords
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConvertDateTimeToWords'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Word'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnknownError'
      parameters:
        - name: x-correlation-id
          in: header
          schema:
            type: string
          required: false
          description: The unique request identifier

  /health:
    get:
      summary: Check the healthapi of the service
      description: Returns a 200 OK response if the service is healthy
      tags:
        - Health
      responses:
        200:
          description: The service is healthy


components:
  schemas:
    Error:
      type: object
      description: Representation of an Error that can appear using the application.
      required:
        - code
        - message
      properties:
        code:
          description: The code of an error that describes the Error.
          type: string
        message:
          description: The message of an error that describes the Error.
          type: string

    ConvertNumberToWords:
      type: object
      description: Convert number to words request representation
      required:
        - number
      properties:
        number:
          description: The number to be converted to words
          type: string

    ConvertWordsToNumber:
      type: object
      description: Convert words to number request representation
      required:
        - words
      properties:
        words:
          description: The words to be converted to number
          type: string

    Word:
      type: object
      description: The number representation in words
      required:
        - words
      properties:
        words:
          description: The number representation in words
          type: string

    Number:
      type: object
      description: Words representation in number
      required:
        - number
      properties:
        number:
          description: Words representation in number
          type: string

    ConvertDateToWords:
      type: object
      description: Convert date to words request representation
      required:
        - date
      properties:
        date:
          description: The date to be converted to words (format: YYYY-MM-DD)
          type: string

    ConvertTimeToWords:
      type: object
      description: Convert time to words request representation
      required:
        - time
      properties:
        time:
          description: The time to be converted to words (format: HH:MM)
          type: string

    ConvertDateTimeToWords:
      type: object
      description: Convert date and time to words request representation
      required:
        - datetime
      properties:
        datetime:
          description: The date and time to be converted to words (format: YYYY-MM-DD HH:MM)
          type: string

  responses:
    UnknownError:
      description: The unknown error appeared. Check your payload or contact support.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    ConvertNumberToWordsResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Word'

    ConvertWordsToNumberResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Number'

  requestBodies:
    ConvertNumberToWordsRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ConvertNumberToWords"

    ConvertWordsToNumberRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ConvertWordsToNumber"

  parameters:
    x-correlation-id:
      in: header
      name: x-correlation-id
      required: false
      description: >
        The unique request identifier
      schema:
        type: string

